### PR TITLE
Created gitignore

### PR DESCRIPTION
**Pull request by duncanmcclean**
For #2

### CODE REVIEW

**Comment by neeraj3029** [comment]
Please add other files types as well, such as pycache and .DS_Store

**Comment by duncanmcclean** [comment]
Made requested changes @neeraj3029

**Review by neeraj3029 — APPROVED** [review]
Thanks @damcclean , just make one last change. Please add venv/ into gitignore file as well. :)

**Comment by duncanmcclean** [comment]
Complete!

**Pull request closed without merging**
